global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:80']  # Target Nginx running on the host
    metrics_path: /nginx_status